### ISSUE TITLE
MaxMind library bindings for v1

### ISSUE THREAD

**Issue by richardhauer** [AndyButland/UmbracoPersonalisationGroupsCore#1]
Seems that only the v1 version of this library is compatible with Umbraco 7, and that it has references to non-strong named versions of Max Mind.

We are experiencing issues with MM and would like to upgrade, but this dependency on an unsigned library is blocking us.

I am happy to fork, but was wondering if you could release an update in the v1 branch that references the strong named versions of the Max Mind libraries so we can update our databases.

Thanks!

**Comment by AndyButland** [comment]
Hi Richard - if you don't mind doing it via a fork, please go ahead.  I can't imagine I'll really make too many updates now to the V7 version of this package with V9 on the way, so it's not as if you'll be falling far behind any other features that might get added.

**Comment by richardhauer** [comment]
OK - just noticed that I forked `Core` instead of the other one.

**Comment by AndyButland** [comment]
Ah yes, you'll want the other repo, not this one.  So I'll close this here, but please let me know how it goes.
