### ISSUE TITLE
Remove unused cookies in Umbraco 10

### ISSUE THREAD

**Issue by ANT-GBR** [AndyButland/UmbracoPersonalisationGroupsCore#10]
Hi Andy,

I want to remove all the cookies that I don't require so I am using the configuration:

```
    "PersonalisationGroups": {
      "ExcludeCriteria": "pagesViewed,numberOfVisits"
    }
```
but this isn't working. I am still seeing personalisationGroupsNumberOfVisitsSessionStarted, personalisationGroupsNumberOfVisits, personalisationGroupsPagesViewed.
The only criteria I need are country and querystring but the below doesn't work either:

```
    "PersonalisationGroups": {
      "IncludeCriteria": "country,querystring"
    }
```

This is in UmbracoPersonalisationGroups 3.2.7

Thanks
Tony

**Comment by ANT-GBR** [comment]
I've added that to ConfigureServices and I'm getting 'Our.Umbraco.PersonalisationGroups.Core.Middleware.TrackUserActivityMiddleware is inaccessible due to its protection level.'

Thanks
Tony

**Comment by AndyButland** [comment]
Ah, of course. So unless you resort to reflection hacks, this will need a release.  Probably best to add a configuration options that allows you disable the user activity tracking if you aren't using it - I'll look at adding that.

**Comment by ANT-GBR** [comment]
Nice one, thanks Andy

**Comment by AndyButland** [comment]
I've just pushed [3.2.8](https://www.nuget.org/packages/UmbracoPersonalisationGroups/3.2.8) which includes a new configuration value.  Setting `DisableUserActivityTracking` to `true` will disable the middleware that does the tracking of user sessions and pages viewed to a cookie.

i.e.:

```
  "Umbraco": {
    "PersonalisationGroups": {
      "DisableUserActivityTracking": true
    }
  }
```

**Comment by ANT-GBR** [comment]
That's awesome, cheers Andy!
