### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by bobhu1** [AndyButland/UmbracoPersonalisationGroupsCore#12]
Got error after install on latest umbraco:

Request error: The URL returned a 404 (not found):
/App_Plugins/PersonalisationGroups/Criteria
![2023-12-03 110905](https://github.com/AndyButland/UmbracoPersonalisationGroupsCore/assets/148344550/607abc15-30a9-49be-aa17-49658825c53a)

**Comment by AndyButland** [comment]
Can I just check you've made both updates necessary to the `Startup.cs` class please?  Am thinking you may have missed `UsePersonalisationGroupsEndpoints()`.
https://github.com/AndyButland/UmbracoPersonalisationGroupsCore#using-the-package

**Comment by tudor7gheorghiu** [comment]
Hi @AndyButland I am currently seeing the same issue but I have the `UsePersonalisationGroupsEndpoints()` code in my Startup class. Do you know what else might be?
