### ISSUE TITLE
Custom criteria Angular code being deleted

### ISSUE THREAD

**Issue by rickbutterfield** [AndyButland/UmbracoPersonalisationGroupsCore#2]
I've created a custom criteria in C# and that works absolute fine, but if I create a custom folder under `App_Plugins/PersonalisationGroups` it gets removed on every build. Currently I think custom ones have to be under this folder to be picked up?

https://github.com/AndyButland/UmbracoPersonalisationGroupsCore/blob/d8a250f843b127661c47a2c747fbcbed2ed23f30/PersonalisationGroups/App_Plugins/PersonalisationGroups/personalisaton-group-definition.controller.js#L83

**Comment by AndyButland** [comment]
Yes, that makes sense - I think this could be problematic.  Will have a look and see what we could do about this, I guess either allowing a different path, or making sure the build process only removes files actually installed by the package.

**Comment by AndyButland** [comment]
Think I've found a resolution to this, though it does involve a small breaking change in the addition of a new property on `IPersonalisationGroupCriteria`, where you can provide a folder for the client-side assets.

Would you mind having a look over the linked PR to see if you think that'll work for you?  And if so, I'll merge it in and push out an update.

**Comment by rickbutterfield** [comment]
@AndyButland Just pulled it into my solution and it's worked a treat! 🎉

**Comment by AndyButland** [comment]
Good to hear, thanks.  Have [released as 3.1.0](https://www.nuget.org/packages/UmbracoPersonalisationGroups/3.1.0).
