### ISSUE TITLE
'Core' version of the package

### ISSUE THREAD

**Issue by LachlannRattray** [AndyButland/UmbracoPersonalisationGroupsCore#4]
Hey Andy

Thanks so much for porting this over to Core, we used it previously on 7 and its been great to work with. One issue we have had recently is that if we want to install the package references into multiple projects there is only 1 NuGet package and it comes with all the app_plugin stuff. 

Would it be feasible to have a Core package that can be installed so that other projects in the solution can have the dll references?

**Comment by AndyButland** [comment]
Sounds like that would be a good idea yes.  I'll try to make this split when I get a bit of time to work on it.

**Comment by AndyButland** [comment]
Hi @LachlannRattray - I've pushed out a new RC release [3.2.0-rc001](https://www.nuget.org/packages/UmbracoPersonalisationGroups/3.2.0-rc001) to NuGet, that has this split.  Would you be able to try it and see if it's set up as makes sense for your solution please?  And if so I can release a full version.

With the change there's a small namespace change - anything that was `Our.Umbraco.PersonalisationGroups.*` is not `Our.Umbraco.PersonalisationGroups.Core.*`.

**Comment by LachlannRattray** [comment]
Hey Andy that's great thank you for doing that. I will get it tested as soon as possible.

**Comment by LachlannRattray** [comment]
Hey Andy just to say we have updated to the new Core package and it seem to work perfectly. thanks very much for doing that!

**Comment by AndyButland** [comment]
Good to hear.  I've released this now as 3.2.0.
