### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by jaymarvels** [AndyButland/UmbracoPersonalisationGroupsCore#6]
Added the package via nuget and when trying to use/build it errors in the generated models (from modelsbuilder)

Running Umb 9.5 and latest version of this package

![image](https://user-images.githubusercontent.com/7057631/171437420-73c2fe2c-2b9f-4b31-b569-7243ca9af347.png)
![image](https://user-images.githubusercontent.com/7057631/171437622-68e8af34-525c-4adf-be8c-dd54c00762f9.png)

**Comment by AndyButland** [comment]
Hmm... I don't seem to be seeing that.  Can I confirm what your models builder configuration is please?  By the looks of it you are using one of the `SourceCode*` models mode options, so can you also confirm where the models are being saved.

I'm wondering perhaps if you are saving them into a project that doesn't have the package referenced?

**Comment by jaymarvels** [comment]
@AndyButland  this was the issue!
